# -*- coding: utf-8 -*-

"""
    sdk

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from sdk.api_helper import APIHelper


class MiscControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(MiscControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.misc

    # Todo: Add description for test test_http_103_123_112_147_5555_auth_register
    def test_http_103_123_112_147_5555_auth_register(self):
        # Parameters for the API call
        username = ''
        password = ''
        password_2 = ''
        email = ''
        first_name = ''
        last_name = ''

        # Perform the API call through the SDK function
        self.controller.http_103_123_112_147_5555_auth_register(username, password, password_2, email, first_name, last_name)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # Todo: Add description for test test_http_103_123_112_147_5555_auth_login
    def test_http_103_123_112_147_5555_auth_login(self):
        # Parameters for the API call
        username = ''
        password = ''

        # Perform the API call through the SDK function
        self.controller.http_103_123_112_147_5555_auth_login(username, password)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

