# -*- coding: utf-8 -*-

"""
    sdk

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from sdk.decorators import lazy_property
from sdk.configuration import Configuration
from sdk.controllers.misc_controller import MiscController


class SdkClient(object):

    config = Configuration

    @lazy_property
    def misc(self):
        return MiscController()


